### ISSUE TITLE
Use .zip(), not `izip!()` for zipping vecs

### ISSUE THREAD

**Issue by bluss** [SuperFluffy/rust-freude#7]
One of them is implemented in libcore and has access to specialization and lots of tricks, the other is a hack from itertools. I've written both, so I mean, it's the same local supplier.

**Comment by bluss** [comment]
Apparently .zip() chained two times doesn't look so good :disappointed:. `azip!()` is better.

Benchmarks [in this file](https://github.com/bluss/rust-ndarray/blob/master/benches/iter.rs). Result with AVX enabled.

```rust
$ RUSTFLAGS=-Ctarget-cpu=native cargo bench --bench iter zip
running 7 tests
test scalar_sum_3_azip             ... bench:       2,288 ns/iter (+/- 97)
test scalar_sum_3_azip_fold        ... bench:       2,369 ns/iter (+/- 34)
test scalar_sum_3_std_zip1         ... bench:       8,450 ns/iter (+/- 299)
test scalar_sum_3_std_zip2         ... bench:       8,449 ns/iter (+/- 78)
test scalar_sum_3_std_zip3         ... bench:       8,268 ns/iter (+/- 80)
test vector_sum_3_azip             ... bench:       4,672 ns/iter (+/- 143)
test vector_sum_3_std_zip          ... bench:       8,165 ns/iter (+/- 319)
```

There may be some way to write it “correctly” using `Iterator::zip` and have it autovectorize.

**Comment by bluss** [comment]
Oh and what must not be forgotten given this issue's topic, itertools izip!() joins the game

```rust
test scalar_sum_3_izip             ... bench:      11,707 ns/iter (+/- 656)
test scalar_sum_3_std_zip1         ... bench:       8,448 ns/iter (+/- 281)
test scalar_sum_3_std_zip2         ... bench:       8,507 ns/iter (+/- 2,610)
test scalar_sum_3_std_zip3         ... bench:       8,265 ns/iter (+/- 409)
test vector_sum_3_azip             ... bench:       4,721 ns/iter (+/- 91)
test vector_sum_3_izip             ... bench:      11,005 ns/iter (+/- 935)
```

**Comment by SuperFluffy** [comment]
That's pretty great that this works for `Vec` as well! I have switched the ndarray version over to `azip!`, and there is no speed difference compared to the brute-force `zip_mut_with_*` version:

```
 name         chaotic_net_prezip.bench ns/iter  chaotic_net_zip.bench ns/iter  diff ns/iter  diff % 
 chaotic_net  189,173,714                       188,670,271                        -503,443  -0.27% 
```

**Comment by bluss** [comment]
Great, that's reassuring!

**Comment by bluss** [comment]
slice and .zip() is supposed to be good, so this is something to investigate further as a Rust bug.

**Comment by SuperFluffy** [comment]
Could this have something to do with external vs internal iterators? https://medium.com/@veedrac/rust-is-slow-and-i-am-the-cure-32facc0fdcb

**Comment by bluss** [comment]
I don't think zip has to do with that. It's basically impossible to have zip adaptor with internal iteration.

There are explicit specializations for Iterator::zip for slices and some other important and simple iterators, and it should ensure for example that  `for (a, b) in a.iter().zip(b) { }` can autovectorize if a, b are slices. It's supposed to work for more than two slices, but appears to not do it.

Or at least.. appears to not work when we observe it in a benchmark.

**Comment by SuperFluffy** [comment]
The shift from `itertools::izip!` to `ndarray::azip!` did not result in any speed gains. But the code is still nicer to read, so this is a gain anyway:

```
 name          kuramoto_prezip.bench ns/iter  kuramoto_zip.bench ns/iter  diff ns/iter  diff % 
 kuramoto_vec  2,234,270                      2,194,456                        -39,814  -1.78%
```

**Comment by bluss** [comment]
ok. Maybe something else entirely is the main work?

**Comment by SuperFluffy** [comment]
Ok, that's exactly what seems to be the case. Inside each integration step, there are 4 expensive derivative-operations. The benches below measure a) how expensive it is to calculate one derivative (for the system at hand), and how b) how expensive one full integration-step is. It's pretty obvious that the derivative calculation completely dominates the operation:

```
running 2 tests
test chaotic_net_derivative ... bench:  49,850,312 ns/iter (+/- 1,459,032)
test chaotic_net_rk4        ... bench: 200,170,184 ns/iter (+/- 1,789,941)
```

**Comment by SuperFluffy** [comment]
Now this looks much better: this is a direct comparison between a pure integration step and a (essentially) non-existing derivative-calculation. No change for the ndarray case, but a major improvement for `Vec`, in case one wants to use that. Great!

```rust
 rk4_array_speed  42,722                    44,096                        1,374    3.22% 
 rk4_vec_speed    63,730                    43,090                      -20,640  -32.39%
```

**Comment by bluss** [comment]
Nice, that makes it clear. Glad to see that the array is entirely on par with the vec.
